name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install VitePlus
        run: npm install -g vite-plus@0.1.22

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Typecheck
        run: vp run check:types

      - name: Test
        run: vp run test

      - name: Release check
        run: vp run release:check
